# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Philsensus
email: jaeheelee0113@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
production_url: "https://jaehee0113.github.io"
url: http://localhost:4000 # the base hostname & protocol for your site, e.g. http://example.com
permalink: /posts/:categories/:title
twitter_username: jaehee0113
github_username:  jaehee0113
youtube_username: jaehee0113
linkedin_username: jaehee0113

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-polyglot
exclude:
  - Gemfile
  - Gemfile.lock

paginate: 10
paginate_path: "/archive/page:num/"

sass:
  sass_dir: _sass
  style: compressed

languages: ["en", "de", "ko"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: false
